-- PRIMARY KEY
--     A primary key is used to ensure data in the specific column is unique. 
--     It is a column cannot have NULL values. 
--     It is either an existing table column or a column that is specifically generated by 
--     the database according to a defined sequence.

-- * Rules For Primary Key
-- 1 A primary key is used to ensure data in the specific.

-- 2 It uniquely identifies a record in the relational database.

-- 3.Only one primary key is allowed in a table.

-- 4.It is a combination of UNIQUE and Not Null constraints. --

-- 5.It does not allow NULL values.

-- 6.Its value cannot be deleted from the parent.

-- 7.It constraint can be implicitly defined on the temporary.


-- Syntax 1. of Primary Key
-- create table categories(
--     categoryId int,
--     categoryname varchar(100),
--     constraint pk_category primary key(categoryId)
-- );

-- insert into categories values(1001,"Electronics");
-- insert into categories values(1002,"Mobiles");

-- select * from categories;

-- ==========================================================

-- Syntax 2. of Primary Key
-- create table categories(
--     categoryId int primary key,
--     categoryname varchar(100),
-- );

-- insert into categories values(1001,"Electronics");
-- insert into categories values(1002,"Mobiles");

-- ==========================================================

-- Syntax 3. of Primary Key
-- create table categories(
--     categoryId int,
--     categoryname varchar(100),
--     primary key(categoryId)   
-- );

-- insert into categories values(1001,"Electronics");
-- insert into categories values(1002,"Mobiles");
